USE [master]
GO

/****** Object:  Database [reto_Guardians]    Script Date: 23/11/2023 11:35:20 a. m. ******/
CREATE DATABASE [reto_Guardians]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'reto_Guardians', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\reto_Guardians.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'reto_Guardians_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\reto_Guardians_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [reto_Guardians].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [reto_Guardians] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [reto_Guardians] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [reto_Guardians] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [reto_Guardians] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [reto_Guardians] SET ARITHABORT OFF 
GO

ALTER DATABASE [reto_Guardians] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [reto_Guardians] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [reto_Guardians] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [reto_Guardians] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [reto_Guardians] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [reto_Guardians] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [reto_Guardians] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [reto_Guardians] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [reto_Guardians] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [reto_Guardians] SET  DISABLE_BROKER 
GO

ALTER DATABASE [reto_Guardians] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [reto_Guardians] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [reto_Guardians] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [reto_Guardians] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [reto_Guardians] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [reto_Guardians] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [reto_Guardians] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [reto_Guardians] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [reto_Guardians] SET  MULTI_USER 
GO

ALTER DATABASE [reto_Guardians] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [reto_Guardians] SET DB_CHAINING OFF 
GO

ALTER DATABASE [reto_Guardians] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [reto_Guardians] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [reto_Guardians] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [reto_Guardians] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [reto_Guardians] SET QUERY_STORE = OFF
GO

ALTER DATABASE [reto_Guardians] SET  READ_WRITE 
GO


